# Generated by Django 5.2.4 on 2025-08-01 00:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("CASAL", "Casal"),
                            ("CERIMONIALISTA", "Cerimonialista"),
                            ("FORNECEDOR", "Fornecedor"),
                            ("ADMIN", "Admin"),
                        ],
                        default="CASAL",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADO", "Aprovado"),
                            ("RECUSADO", "Recusado"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Casal",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome_noivo", models.CharField(max_length=100)),
                ("nome_noiva", models.CharField(max_length=100)),
                ("data_casamento", models.DateField()),
                (
                    "orcamento_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome_empresa", models.CharField(max_length=255)),
                (
                    "categoria_servico",
                    models.CharField(
                        choices=[
                            ("BUFFET", "Buffet"),
                            ("DECORACAO", "Decoração"),
                            ("FOTOGRAFIA", "Fotografia"),
                            ("MUSICA", "Música"),
                            ("ESPACO", "Espaço"),
                            ("CONVITES", "Convites"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contato_email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo_contrato", models.FileField(upload_to="contratos/")),
                ("assinado", models.BooleanField(default=False)),
                ("data_assinatura", models.DateField(blank=True, null=True)),
                (
                    "orcamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrato",
                        to="casamento.orcamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("ATRASADO", "Atrasado"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[("A_VISTA", "À Vista"), ("PARCELADO", "Parcelado")],
                        max_length=10,
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(blank=True, null=True, upload_to="comprovantes/"),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="casamento.orcamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evento", models.CharField(max_length=255)),
                ("data_evento", models.DateTimeField()),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "casal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="casamento.casal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_limite", models.DateField()),
                ("concluida", models.BooleanField(default=False)),
                (
                    "prioridade",
                    models.IntegerField(
                        choices=[(1, "Baixa"), (2, "Média"), (3, "Alta")], default=2
                    ),
                ),
                (
                    "casal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="casamento.casal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orcamento",
            name="casal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orcamentos",
                to="casamento.casal",
            ),
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "casal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="casamento.casal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cerimonialista",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "casais",
                    models.ManyToManyField(
                        related_name="cerimonialistas", to="casamento.casal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField()),
                ("local", models.CharField(max_length=255)),
                ("anotacoes", models.TextField(blank=True, null=True)),
                (
                    "casal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas",
                        to="casamento.casal",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas",
                        to="casamento.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orcamento",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orcamentos",
                to="casamento.fornecedor",
            ),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comentario", models.TextField()),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "casal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="casamento.casal",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="casamento.fornecedor",
                    ),
                ),
            ],
        ),
    ]
